<a href="https://colab.research.google.com/github/cs16677/ce888/blob/master/lab1/tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1.

In [34]:
import numpy as np

array = np.random.randint(0, 50, (4,2))
print(array)

[[16 15]
 [47 10]
 [16 30]
 [ 6 23]]


##2.

In [10]:
array = np.random.randint(0, 101, 10)
print("Unsorted: ", array)
print("Sorted Ascending: ", np.sort(array))
print("Sorted Descending: ", np.sort(array)[::-1])

Unsorted:  [45 95 12 77 39 10 45  8  3 97]
Sorted Ascending:  [ 3  8 10 12 39 45 45 77 95 97]
Sorted Descending:  [97 95 77 45 45 39 12 10  8  3]


##3.

In [39]:
arr = [1,2,3,4,5,6,7,8,9]
print(np.reshape(arr, (3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##4.

In [37]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[1,2],[3,4]])
print("Rows: ", np.concatenate((x1, x2)))
print("Columns: ", np.concatenate((x1, x2), axis=1))

Rows:  [[1 2]
 [3 4]
 [1 2]
 [3 4]]
Columns:  [[1 2 1 2]
 [3 4 3 4]]


##5.

In [38]:
arr1 = np.array([1,4,5,7,8,11,13,16])
arr2 = np.array([2,3,5,11,15,16,27,31])

print(np.intersect1d(arr1, arr2))

[ 5 11 16]


##6.

In [54]:
arr = np.array([[1,2,3,3,4], 
               [5,7,3769,4578,5], 
               [3,49,26,7856,45], 
               [564,32,4876,2,786], 
               [9,40,46,46,786]])
print("max(Columns):",np.amax(arr, axis=0))
print("min(Columns):",np.amin(arr, axis=0))
print("max(Rows):",np.amax(arr, axis=1))
print("min(Rows):",np.amin(arr, axis=1))

max(Columns): [ 564   49 4876 7856  786]
min(Columns): [1 2 3 2 4]
max(Rows): [   4 4578 7856 4876  786]
min(Rows): [1 5 3 2 9]


##7.

In [56]:
arr = np.random.randint(0, 200, 100)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 91.5
Median: 88.0
Standard Deviation: 53.743371684329595


##8.

In [62]:
import sklearn.preprocessing as pp

arr = np.random.randint(0, 100, (5,5))
print(pp.normalize(arr))

[[0.09723694 0.51859703 0.24309236 0.59152473 0.55911242]
 [0.43614383 0.46083122 0.65010118 0.41145644 0.07406216]
 [0.48307795 0.55299713 0.47036538 0.48943424 0.00635629]
 [0.84055407 0.11886623 0.34810825 0.38207003 0.11037579]
 [0.30975358 0.52586072 0.57628572 0.44662144 0.30975358]]


##9.

In [69]:
arr3d = np.random.randint(0, 100, (4,4,3))
arr2d = np.random.randint(0, 100, (4,4))
print(np.tensordot(arr3d, arr2d, axes=([0,1], [0,1])))

[24279 29361 33998]
